### ISSUE TITLE
[Bug] Unable to sign-in to a self-hosted plane

### ISSUE THREAD

**Issue by thelazyoxymoron** [makeplane/plane-mobile#13]
When trying to sign-in to a self-hosted instance of Plane, getting the following error:

![plane_crash](https://github.com/makeplane/plane-mobile/assets/9106868/194eaa25-d196-42d4-922c-036bedb38331)

**Comment by rameshkumarchandra** [comment]
Please check if you have `/api` in your base url. If it is there then remove it. It should be like `http://<your_ip|domain_name>`

**Comment by thelazyoxymoron** [comment]
Thanks, that worked.
