### ISSUE TITLE
[🚨 Compiler]: Migrate to Android embedding v2

### ISSUE THREAD

**Issue by guy-av** [makeplane/plane-mobile#82]
# Issue

The plugin `connectivity_plus` requires the app to be migrated to the Android embedding v2.

Currently unable to run the app without migrating.

[Migration documentation](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)

## Output

```
$ flutter run

This app is using a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
Take a look at the docs for migrating an app: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
The plugin `connectivity_plus` requires your app to be migrated to the Android embedding v2. Follow the steps on the migration doc above and re-run this command.
```

## Machine

- MacBook Pro M1
- Flutter 3.13.3 • channel stable

**Comment by rameshkumarchandra** [comment]
Hey @guy-av, create a file named `AndroidManifest.xml` in the `android/app/src/main` directory. In this directory, you will find a file called `AndroidManifest.xml.template`. Copy the contents from `AndroidManifest.xml.template` and paste them into the newly created `AndroidManifest.xml` file. After completing this step, try running the code. 

Please note that we will be adding detailed setup steps to the README file soon.

**Comment by guy-av** [comment]
Thanks for the help @rameshkumarchandra!

I wonder, why git-ignore `AndroidManifest.xml`? Shouldn't the template be committed to the repo?

**Comment by yahu1031** [comment]
@guy-av So basically the idea is that the original files will be having additional configurations where we need to inject API keys and may not be used while developers use this code. So template is basically a generic code that can be used.

**Comment by yahu1031** [comment]
@rameshkumarchandra Hoping this was fixed. Please close it.
